// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3a4Cmn9WmrtMomFS1KOzCvWQd3Vm9Ts',
    appId: '1:249626610183:web:ba7b3c82afd50345e438a2',
    messagingSenderId: '249626610183',
    projectId: 'vitom-e47d9',
    authDomain: 'vitom-e47d9.firebaseapp.com',
    databaseURL: 'https://vitom-e47d9-default-rtdb.firebaseio.com',
    storageBucket: 'vitom-e47d9.appspot.com',
    measurementId: 'G-4DZYLQ5104',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9GTkbTQIiDj6-tRn7ljgJumIcFYtyfo',
    appId: '1:249626610183:android:d3fa8846fe5d6034e438a2',
    messagingSenderId: '249626610183',
    projectId: 'vitom-e47d9',
    databaseURL: 'https://vitom-e47d9-default-rtdb.firebaseio.com',
    storageBucket: 'vitom-e47d9.appspot.com',
  );
}
